export const deepQuestions = [
  // Original questions
  "What's a childhood memory that still makes you smile?",
  "If you could have dinner with anyone, living or dead, who would it be and why?",
  "What's something you've learned about yourself this year?",
  "What would you do if you knew you couldn't fail?",
  "What's the best advice someone has ever given you?",
  "What are you most grateful for right now?",
  "If you could change one thing about the world, what would it be?",
  "What's a fear you've overcome or are working to overcome?",
  "What makes you feel most alive?",
  "What's something you wish people knew about you?",
  "What's a moment that changed your perspective on life?",
  "If you could master any skill instantly, what would it be?",
  "What's something you've always wanted to try but haven't yet?",
  "What does success mean to you?",
  "What's the most important lesson you've learned from a mistake?",
  "If you could give your younger self one piece of advice, what would it be?",
  "What's something that always makes you laugh?",
  "What's a goal you're working toward right now?",
  "What's something you admire about your closest friends?",
  "What's a small act of kindness that had a big impact on you?",
  
  // New questions
  "What was the best part of your day? Week? Year?",
  "Tell me something about yourself that you wouldn't mention the first time you met someone.",
  "What's the best gift you've ever given or received?",
  "What's your aesthetic? How did you arrive at it?",
  "Do you have any nicknames? If so, what's the story behind them?",
  "When was the last time you did something for the first time?",
  "What is your latest discovery about the city in which you live?",
  "Would you like to be famous? In what way or for what?",
  "What's your best memory from high school?",
  "What's the best compliment you've ever received?",
  "What would constitute a perfect day for you?",
  "If you could gain any quality or ability, what would it be?",
  "Give the choice of anyone in the world, who would you want as a dinner guest?",
  "What's a work (book, movie, etc.) that shaped the person you are today?",
  "Tell me about a time that you were spontaneous.",
  "What's the most illegal act you've ever done and are comfortable sharing?",
  "When did you last leave your comfort zone?",
  "What was your last epiphany?",
  "Would you pick a different career path if you did life again?",
  "What's one specific fact about what it's like to live in your particular body?",
  
  // Deep questions
  "What was your most memorable first kiss?",
  "With whom do you have the best connection in your family? Why?",
  "What's the most memorable date you've ever had?",
  "Tell me about your biggest crush.",
  "Who do you respect most in your life? Why?",
  "Do you have an enemy? If so, why?",
  "How did your best friend become your best friend?",
  "How did your parents' values shape your career choice?",
  "What do you value most in a friendship?",
  "For what in the past year do you feel most grateful?",
  "Is there something you've dreamed of doing for a long time? Why haven't you done it?",
  "What's your greatest accomplishment?",
  "What's an embarrassing moment in your life that you still remember?",
  "What does it mean to you to live a good life?",
  "What experience have you had that made you a more compassionate person?",
  "When was the last time you faced a big ethical dilemma? What did you do?",
  "What brings you joy?",
  "Do you feel fulfilled by your work? Why or why not?",
  "When was the last time you were really proud of yourself?",
  "What's the most important self-discovery you made about yourself in the past year?",
  "What's an experience in your past that really shaped your worldview? Why?",
  "How do you hope you'll change as a person in the future?",
  "What excites you most about the world in which we live?",
  "What frustrates you most about the world in which we live?",
  "What are three of your personal qualities of which you're most proud?",

  // Additional deep questions
  "What's the best question you've ever been asked?",
  "Who's the most influential person in your life?",
  "Where would you be if you hadn't followed your dream?",
  "What's the best decision you've ever made in your life?",
  "What's your deepest regret and how can you forgive yourself or make amends?",
  "What interests you about the person sitting across from (or next to you)?",
  "What's your biggest pet peeve?",
  "What's a red flag about you?",
  "What's a green flag about you?",
  "What color are you (in mood or feeling) and why?",
  "What helps you breathe easy?",
  "What do you have faith in right now?",
  "What's changing in your life (for the better)?",
  "Who's the most joyful person you've ever met?",
  "What's been the best moment of your life so far?",
  "Do you believe in second chances?",
  "What's something the person across from you doesn't know about you?",
  "If you could teleport to any location, where would it be?",
  "Are you honest?",
  "Are you going through anything the person across from you doesn't know about?",
  "Who do you trust most in life?",
  "What's most important to you right now?",
  "What question can't you seem to find the answer to?",
  "What's the biggest \"what if\" in your mind?",
  "What's the first thing that comes to mind when you think of success?",
  "What's the question you want to ask most? To whom and why?",
  "Who is someone you wish was still around?",
  "How have you shown up for yourself lately?",
  "What's your worst tendency?",
  "What's your best quality?",
  "What's your superpower?",
  "What's the superpower of the person across from you?",
  "If you could receive closure from one person, who would it be?",
  "Are you resisting change? If so, why?",
  "In your own words, what does love mean?",
  "In your own words, what does self-worth mean?",
  "Have you made space in your life for what you want?",
  "What's a moment you will cherish forever?",
  "If you could tell your childhood crush one thing, what would it be?",
  "How do you handle anger?",
  "What's special about this moment?",
  "What's been the miracle in the mundane for you lately?",
  "Where have you felt most rejected?",
  "Where have you felt most accepted?",
  "What have you learned about yourself in the past year?",
  "What about yourself do you have trouble acknowledging?",
  "What has been your most valuable life lesson?",
  "What do you need most right now?",
  "What are you looking forward to?",
  "Who always has your best interest in mind?",
  "If you could give someone a star on the Walk Of Fame in your life, who would it be?",
  "What scares you the most?",
  "What's the most sacred thing about you?",
  "What life lesson have you learned the hard way?",
  "What makes you stand out in the crowd?",
  "What's something that shocked you about the person sitting next to you?",
  "What's been your biggest challenge in life and how did you overcome it?",
  "What shocks you about yourself?",
  "Is there a dream you're hiding from others?",
  "If you could adopt another perspective about life, what would it be?",
  "If you could ask God, Life, The Angels, or Powers That Be any question (and receive a direct answer), what would it be?",
  "What's one thought-provoking question you would ask? Ask it.",
  "If you could bestow a superpower on a loved one, what would it be?"
];

export function getRandomQuestion(): string {
  return deepQuestions[Math.floor(Math.random() * deepQuestions.length)];
}